### ISSUE TITLE
HTTP error 500

### ISSUE THREAD

**Issue by FabA7** [Agence-DnD/PIMGento-API#2]
Hi,

I just tried to install the module following the process: 

• Copy last release content in Magento root
• Use composer in Magento root to install required library:
composer require php-http/guzzle6-adapter:^1.1
composer require akeneo/api-php-client-ee:^3.0
• Clear the cache (System > Cache Management)

At the moment to clean the cache I get this error from the log with an error 500: 
PHP Fatal error:  Uncaught Error: Call to a member function dropMainTable() on boolean in /var/www/html/mywebsite/app/code/community/Pimgento/Api/sql/pimgento_api_setup/install-1.0.0.php:19\nStack trace:\n#0 /var/www/html/mywebsite/includes/src/Mage_Core_Model_Resource_Setup.php

Can you help me find this out please ?
• Magento 1.9.3.10
• PHP 7.1.26

Thanks in advance!

BR,
Fab

**Comment by Dnd-Gimix** [comment]
Hello @FabA7 ,

Thank you for using PIMGento API !

Do you have any other cache system activated : 
- Magento compilation ?
- PHP cache ?
- Varnish ?

Thank you.

Regards,

**Comment by FabA7** [comment]
Hi @Dnd-Gimix,

Thank you for this fast answer!

I don't have any Varnish, but just to tell you what I did after your message:
• Remove the /app files from the module to access the Magento admin interface
• clear + deactivate the PHP cache and the compilation
then
• paste back the /app files
• reactivate the cache and launch the compilation process

I don't have the HTTP error 500 anymore. Thanks a lot!
Next step :)

BR,
Fab

**Comment by Dnd-Gimix** [comment]
@FabA7 ,

Glad everything worked out ;)

Have a nice day !

BR,
