### ISSUE TITLE
Import categories inside Magento default category 

### ISSUE THREAD

**Issue by FabA7** [Agence-DnD/PIMGento-API#3]
Hi DnD,

Could you tell me please, if I have a possibility to import my categories from Akeneo to the Magento, inside default category folder?
Because I already have an existing categories structure from an production website, working with another PIM which will disappear in the future.

I tried to reproduce the same model in Akeneo including this Default Category + Products, but it doesn't make the job.

That's my desired structure
![capture](https://user-images.githubusercontent.com/45561813/51607088-fb273080-1f13-11e9-9145-590afec661d5.JPG)

Could you suggest me please what I can do?

Thanks in advance.

BR,
Fab

**Comment by Dnd-Gimix** [comment]
Hello @FabA7 ,

It is not possible to import an Akeneo category structure inside the "Default category" of Magento, it will always create news trees based on your Akeneo structure.

My advise would be to : 

- Import all trees from your Akeneo
- Move your "Produits" category to the tree you want to use in the future
- Assign the new category tree to your website 

That should do the trick. You'll have to make sure that your current PIM integration will still be linked to the moved category "Produits" as well.
Please come back to me to confirm that it helped you.

Have a good day !

Regards,

**Comment by FabA7** [comment]
Yes @Dnd-Gimix,

That's what I was thinking, if you tell me it's not possible :)
Thanks a lot for the fast answer !

Br,
Fab

**Comment by Dnd-Gimix** [comment]
Perfect 👍 , thank you for your answer @FabA7 .

I'll close this issue.

Regards,
