### ISSUE TITLE
Api test failed: Not Found

### ISSUE THREAD

**Issue by davidverbeek** [Agence-DnD/PIMGento-API#38]
Hello,

I installed pimgento api in magento 1.9. After saving the api credentials when I click on "Test" button it is giving "Api test failed: Not Found" error, as shown in below screen shot.

![error](https://user-images.githubusercontent.com/50629081/69795915-0ceff900-11f3-11ea-9325-f710abcc049a.png)

Please help.

**Comment by janssensjelle** [comment]
The url seems incorrect to me? Is this a local environment? Does your Magento know that your test domain links to a local env?

**Comment by davidverbeek** [comment]
Thanks @janssensjelle , for your reply.  The problem was we have to save the configuration first and then click on the "Test" button.

This issue is resolved now thanks.
